services:
    Enhavo\Bundle\ApiBundle\Controller\DocumentationController:
        arguments:
            - '@Enhavo\Bundle\ApiBundle\Documentation\DocumentationGenerator'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: controller.service_arguments }
            - { name: container.service_subscriber }

    Enhavo\Bundle\ApiBundle\EventListener\EndpointRouteListener:
        arguments:
            - '@Enhavo\Component\Type\FactoryInterface[Endpoint]'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: -100 }

    Enhavo\Bundle\ApiBundle\Routing\Loader\EndpointDirectoryLoader:
        arguments:
            - '@file_locator'
            - '@Enhavo\Bundle\ApiBundle\Routing\Loader\AttributeRouteEndpointLoader'
        tags:
            - { name: routing.loader }

    Enhavo\Bundle\ApiBundle\Routing\Loader\AttributeRouteEndpointLoader:
        arguments:
            - '%kernel.environment%'

    Enhavo\Bundle\ApiBundle\Documentation\DocumentationGenerator:
        arguments:
            - '%enhavo_api.documentation%'

    Enhavo\Bundle\ApiBundle\Documentation\InfoDescriber:
        tags:
            - { name: enhavo_api.documentation_describer}

    Enhavo\Bundle\ApiBundle\Documentation\RouteDescriber:
        arguments:
            - '@router'
        calls:
            - [ setEndpointFactory, [ '@Enhavo\Component\Type\FactoryInterface[Endpoint]' ] ]
        tags:
            - { name: enhavo_api.documentation_describer}

    Enhavo\Bundle\ApiBundle\Normalizer\DataNormalizer:
        tags:
            - { name: serializer.normalizer }

    Enhavo\Bundle\ApiBundle\Profiler\EndpointDataCollector:
        tags:
            - { name: data_collector, id: 'endpoint', priority: 100 }

    Enhavo\Component\Type\FactoryInterface[Endpoint]:
        class: Enhavo\Bundle\ApiBundle\Factory\EndpointFactory
        arguments:
            - 'Enhavo\Bundle\ApiBundle\Endpoint\Endpoint'
            - '@Enhavo\Component\Type\RegistryInterface[Endpoint]'
            - '@Enhavo\Bundle\ApiBundle\Profiler\EndpointDataCollector'

    Enhavo\Bundle\ApiBundle\Twig\ApiProfilerExtension:
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\ApiBundle\Normalizer\DataDataNormalizer:
        tags:
            - { name: enhavo_api.data_normalizer }


    Enhavo\Bundle\ApiBundle\Command\CreateDocsCommand:
        arguments:
            - '@Enhavo\Bundle\ApiBundle\Documentation\DocumentationGenerator'
            - '@filesystem'
        tags:
            - { name: console.command }
