enhavo_content:
    structured_data:
        Enhavo\Bundle\BlockBundle\Entity\Node:
            properties:
                block:
                    -
                        type: model
                children:
                    -
                        type: model
