services:
    '@enhavo/app/action/ActionFactory':
        import: ActionFactory

    '@enhavo/app/action/ActionManager':
        import: ActionManager
        chunk: 'app'
        arguments:
            - '@enhavo/app/action/ActionFactory'
        tags:
            - { name: vue.service, service: 'actionManager' }
