#!/usr/bin/env bash
# Execute all php unit tests

#bin/phpunit --configuration tests/App/phpunit.xml

bundles=(\
AppBundle \
ArticleBundle \
BlockBundle \
CalendarBundle \
CommentBundle \
ContactBundle \
ContentBundle \
DashboardBundle \
FormBundle \
MediaBundle \
NavigationBundle \
NewsletterBundle \
PageBundle \
PortalBundle \
RedirectBundle \
RevisionBundle \
RoutingBundle \
SearchBundle \
SettingBundle \
ShopBundle \
SidebarBundle \
SliderBundle \
TaxonomyBundle \
TemplateBundle \
ThemeBundle \
TranslationBundle \
UserBundle \
)

for bundle in ${bundles[*]}
do
    bin/phpunit --configuration src/Enhavo/Bundle/$bundle/phpunit.xml "$@"
done