<?php

namespace Enhavo\Bundle\TranslationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TranslationStringsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationStringsRepository extends EntityRepository
{
}
