<?php

/*
 * This file is part of the enhavo package.
 *
 * (c) WE ARE INDEED GmbH
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Enhavo\Bundle\TranslationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Enhavo\Bundle\TranslationBundle\Entity\TranslationRoute;

/**
 * TranslationRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationRouteRepository extends EntityRepository
{
    /**
     * @return array|TranslationRoute[]
     */
    public function findTranslationRoutes($class, $id, ?string $property = null, ?string $locale = null): array
    {
        $qb = $this->createQueryBuilder('tr')
            ->join('tr.route', 'r')
            ->andWhere('r.contentClass = :class')
            ->andWhere('r.contentId = :id')
            ->setParameter('class', $class)
            ->setParameter('id', $id)
        ;

        if ($locale !== null) {
            $qb->andWhere('tr.locale = :locale');
            $qb->setParameter('locale', $locale);
        }

        if ($property !== null) {
            $qb->andWhere('tr.property = :property');
            $qb->setParameter('property', $property);
        }

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
