<?php

namespace Enhavo\Bundle\TranslationBundle\Repository;

use Enhavo\Bundle\AppBundle\Repository\EntityRepository;

/**
 * TranslationStringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationStringRepository extends EntityRepository
{
}
