enhavo_media_theme_file:
    path:  /media/file/{token}/{shortChecksum}/{basename}
    methods: [GET]
    requirements:
        basename: .+
    defaults:
        extension: ~
        _expose: [theme]
        _endpoint:
            type: media_file
            permission: ~
            repository_arguments:
                - token: expr:request.attributes,get("token")
                  filename: 'expr:pathinfo(request.attributes.get("basename"),8)'
                  extension: 'expr:pathinfo(request.attributes.get("basename"),4)'
                  shortChecksum: expr:request.attributes.get("shortChecksum")
