enhavo_media_theme_format:
    path: /media/format/{token}/{format}/{shortChecksum}/{basename}
    methods: [GET]
    requirements:
        basename: .+
    defaults:
        extension: ~
        _expose: [theme]
        _endpoint:
            type: media_format
            permission: ~
            repository_arguments:
                - token: expr:request.query.get("token")
                  filename: 'expr:pathinfo(request.query.get("basename"),8)'
                  shortChecksum: expr:request.query.get("shortChecksum")
