<?php

namespace Enhavo\Bundle\DemoBundle\Repository;

use Enhavo\Bundle\AppBundle\Repository\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{

}
