<?php

namespace Enhavo\Bundle\DemoBundle\Repository;

use Enhavo\Bundle\AppBundle\Repository\EntityRepository;

/**
 * MagazineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazineRepository extends EntityRepository
{
}
