enhavo_translation:
    enable: '%env(bool:TRANSLATION_ENABLED)%'
    default_locale: '%locale%'
    locales:
        - 'en'
        - 'de'
        - 'fr'
    translation_client:
        deepl:
            api_key: '%env(DEEPL_API_KEY)%'
