#!/usr/bin/env php
<?php

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

$loader = require __DIR__.'/../app/autoload.php';
require_once __DIR__.'/../app/bootstrap.php.cache';

set_time_limit(0);

$environment = new Environment();

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), $environment->getEnvironment());
$debug = !$input->hasParameterOption(array('--no-debug', '')) && $environment->isDebug();

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);
