enhavo_translation:
    metadata:
        Enhavo\Bundle\NavigationBundle\Entity\Link:
            properties:
                link:
                    type: slug
                    allow_fallback: true

        Enhavo\Bundle\NavigationBundle\Entity\Navigation:
            properties:
                nodes:
                    type: model

        Enhavo\Bundle\NavigationBundle\Entity\Node:
            properties:
                label:
                    type: text
                    allow_fallback: true
                children:
                    type: model
                subject:
                    type: model
