<?php

namespace Enhavo\Bundle\ContentBundle\Repository;

use Enhavo\Bundle\AppBundle\Repository\EntityRepository;

/**
 * RedirectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectRepository extends EntityRepository
{
}
