import "@enhavo/theme/init"
import "@enhavo/block/init"
import "@enhavo/slider/init"
import "@enhavo/shop/init"
import "@enhavo/article/init"
import "@enhavo/calendar/init"
import "@enhavo/media/init"
import Container from "@enhavo/app/theme"
