<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle::class => ['all' => true],
    FOS\JsRoutingBundle\FOSJsRoutingBundle::class => ['all' => true],
    Bazinga\Bundle\HateoasBundle\BazingaHateoasBundle::class => ['all' => true],
    BabDev\PagerfantaBundle\BabDevPagerfantaBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Sylius\Bundle\ResourceBundle\SyliusResourceBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    Enhavo\Bundle\AppBundle\EnhavoAppBundle::class => ['all' => true],
    Enhavo\Bundle\UserBundle\EnhavoUserBundle::class => ['all' => true],
    Enhavo\Bundle\MediaBundle\EnhavoMediaBundle::class => ['all' => true],
    Enhavo\Bundle\MediaLibraryBundle\EnhavoMediaLibraryBundle::class => ['all' => true],
    Enhavo\Bundle\SearchBundle\EnhavoSearchBundle::class => ['all' => true],
    Enhavo\Bundle\FormBundle\EnhavoFormBundle::class => ['all' => true],
    Enhavo\Bundle\DashboardBundle\EnhavoDashboardBundle::class => ['all' => true],
    Enhavo\Bundle\ArticleBundle\EnhavoArticleBundle::class => ['all' => true],
    Enhavo\Bundle\PageBundle\EnhavoPageBundle::class => ['all' => true],
    Enhavo\Bundle\BlockBundle\EnhavoBlockBundle::class => ['all' => true],
    Enhavo\Bundle\TaxonomyBundle\EnhavoTaxonomyBundle::class => ['all' => true],
    Enhavo\Bundle\SliderBundle\EnhavoSliderBundle::class => ['all' => true],
    Enhavo\Bundle\SettingBundle\EnhavoSettingBundle::class => ['all' => true],
    Enhavo\Bundle\NewsletterBundle\EnhavoNewsletterBundle::class => ['all' => true],
    Enhavo\Bundle\CalendarBundle\EnhavoCalendarBundle::class => ['all' => true],
    Enhavo\Bundle\ContentBundle\EnhavoContentBundle::class => ['all' => true],
    Enhavo\Bundle\ContactBundle\EnhavoContactBundle::class => ['all' => true],
    Enhavo\Bundle\CommentBundle\EnhavoCommentBundle::class => ['all' => true],
    Enhavo\Bundle\DoctrineExtensionBundle\EnhavoDoctrineExtensionBundle::class => ['all' => true],
    Enhavo\Bundle\RoutingBundle\EnhavoRoutingBundle::class => ['all' => true],
    Enhavo\Bundle\NavigationBundle\EnhavoNavigationBundle::class => ['all' => true],
    Enhavo\Bundle\ThemeBundle\EnhavoThemeBundle::class => ['all' => true],
    Enhavo\Bundle\TranslationBundle\EnhavoTranslationBundle::class => ['all' => true],
    Enhavo\Bundle\RedirectBundle\EnhavoRedirectBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Enhavo\Bundle\ShopBundle\EnhavoShopBundle::class => ['all' => true],
    Enhavo\Bundle\SidebarBundle\EnhavoSidebarBundle::class => ['all' => true],
    Enhavo\Bundle\TemplateBundle\EnhavoTemplateBundle::class => ['all' => true],
    Enhavo\Bundle\MultiTenancyBundle\EnhavoMultiTenancyBundle::class => ['all' => true],
    Enhavo\Bundle\VueFormBundle\EnhavoVueFormBundle::class => ['all' => true],
    Sylius\Bundle\PaymentBundle\SyliusPaymentBundle::class => ['all' => true],
    Sylius\Bundle\MoneyBundle\SyliusMoneyBundle::class => ['all' => true],
    Sylius\Bundle\OrderBundle\SyliusOrderBundle::class => ['all' => true],
    Sylius\Bundle\PromotionBundle\SyliusPromotionBundle::class => ['all' => true],
    Sylius\Bundle\ShippingBundle\SyliusShippingBundle::class => ['all' => true],
    Sylius\Bundle\LocaleBundle\SyliusLocaleBundle::class => ['all' => true],
    Sylius\Bundle\AttributeBundle\SyliusAttributeBundle::class => ['all' => true],
    Sylius\Bundle\ProductBundle\SyliusProductBundle::class => ['all' => true],
    Sylius\Bundle\AddressingBundle\SyliusAddressingBundle::class => ['all' => true],
    Sylius\Bundle\CurrencyBundle\SyliusCurrencyBundle::class => ['all' => true],
    Sylius\Bundle\InventoryBundle\SyliusInventoryBundle::class => ['all' => true],
    Sylius\Bundle\TaxationBundle\SyliusTaxationBundle::class => ['all' => true],
    Payum\Bundle\PayumBundle\PayumBundle::class => ['all' => true],
    winzou\Bundle\StateMachineBundle\winzouStateMachineBundle::class => ['all' => true],
];
