<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle::class => ['all' => true],
    BabDev\PagerfantaBundle\BabDevPagerfantaBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    winzou\Bundle\StateMachineBundle\winzouStateMachineBundle::class => ['all' => true],
    Enhavo\Bundle\ApiBundle\EnhavoApiBundle::class => ['all' => true],
    Enhavo\Bundle\AppBundle\EnhavoAppBundle::class => ['all' => true],
    Enhavo\Bundle\UserBundle\EnhavoUserBundle::class => ['all' => true],
    Enhavo\Bundle\MediaBundle\EnhavoMediaBundle::class => ['all' => true],
    Enhavo\Bundle\MediaLibraryBundle\EnhavoMediaLibraryBundle::class => ['all' => true],
    Enhavo\Bundle\SearchBundle\EnhavoSearchBundle::class => ['all' => true],
    Enhavo\Bundle\FormBundle\EnhavoFormBundle::class => ['all' => true],
    Enhavo\Bundle\DashboardBundle\EnhavoDashboardBundle::class => ['all' => true],
    Enhavo\Bundle\ArticleBundle\EnhavoArticleBundle::class => ['all' => true],
    Enhavo\Bundle\PageBundle\EnhavoPageBundle::class => ['all' => true],
    Enhavo\Bundle\BlockBundle\EnhavoBlockBundle::class => ['all' => true],
    Enhavo\Bundle\TaxonomyBundle\EnhavoTaxonomyBundle::class => ['all' => true],
    Enhavo\Bundle\SettingBundle\EnhavoSettingBundle::class => ['all' => true],
    Enhavo\Bundle\NewsletterBundle\EnhavoNewsletterBundle::class => ['all' => true],
    Enhavo\Bundle\CalendarBundle\EnhavoCalendarBundle::class => ['all' => true],
    Enhavo\Bundle\ContentBundle\EnhavoContentBundle::class => ['all' => true],
    Enhavo\Bundle\ContactBundle\EnhavoContactBundle::class => ['all' => true],
    Enhavo\Bundle\CommentBundle\EnhavoCommentBundle::class => ['all' => true],
    Enhavo\Bundle\DoctrineExtensionBundle\EnhavoDoctrineExtensionBundle::class => ['all' => true],
    Enhavo\Bundle\ResourceBundle\EnhavoResourceBundle::class => ['all' => true],
    Enhavo\Bundle\RevisionBundle\EnhavoRevisionBundle::class => ['all' => true],
    Enhavo\Bundle\RoutingBundle\EnhavoRoutingBundle::class => ['all' => true],
    Enhavo\Bundle\NavigationBundle\EnhavoNavigationBundle::class => ['all' => true],
    Enhavo\Bundle\TranslationBundle\EnhavoTranslationBundle::class => ['all' => true],
    Enhavo\Bundle\RedirectBundle\EnhavoRedirectBundle::class => ['all' => true],
    Enhavo\Bundle\TemplateBundle\EnhavoTemplateBundle::class => ['all' => true],
    Enhavo\Bundle\MultiTenancyBundle\EnhavoMultiTenancyBundle::class => ['all' => true],
    Enhavo\Bundle\VueFormBundle\EnhavoVueFormBundle::class => ['all' => true],
];
