enhavo_resource:
    resources:
        enhavo_setting.setting:
            priority: -10
            classes:
                model: Enhavo\Bundle\SettingBundle\Entity\Setting
                factory: Enhavo\Bundle\ResourceBundle\Factory\Factory
                repository: Enhavo\Bundle\SettingBundle\Repository\SettingRepository
    grids:
        enhavo_setting.setting:
            class: Enhavo\Bundle\ResourceBundle\Grid\Grid
            actions:
                filter:
                    type: filter
            filters:
                label:
                    type: text
                    property: label
                    label: setting.label.setting
                    translation_domain: EnhavoSettingBundle
                    initial_active: true

            routes:
                list_parameters:
                    group: expr:request.query.get("group")
            resource: enhavo_setting.setting
            collection:
                criteria:
                    group: expr:request.query.get("group")
            columns:
                label:
                    type: text
                    property: label
                    label: setting.label.label
                    translation_domain: EnhavoSettingBundle
                    width: 6
                value:
                    type: setting
                    label: setting.label.value
                    translation_domain: EnhavoSettingBundle
                    width: 6

    inputs:
        enhavo_setting.setting:
            extends: enhavo_resource.input
            resource: enhavo_setting.setting
            form: Enhavo\Bundle\SettingBundle\Form\Type\SettingType
            form_options: {  }
            actions_secondary:
                delete:
                    type: delete
                    enabled: false
            tabs:
                main:
                    type: form
                    arrangement: |
                        name
                        value.value

        enhavo_setting.setting_key:
            extends: enhavo_setting.setting
            repository_method: findOneByKey
            repository_arguments:
                - 'expr:request.attributes.get("key")'
            actions:
                save:
                    type: save
                    route: enhavo_setting_admin_api_setting_update
