enhavo_resource:
    grids:
        enhavo_article.tag:
            extends: enhavo_taxonomy.term_table
            collection:
                repository_arguments:
                    - 'article_tag'
            permission: ROLE_ENHAVO_ARTICLE_TAG_INDEX
            actions:
                create:
                    type: create
                    permission: ROLE_ENHAVO_ARTICLE_TAG_CREATE
                    route: 'expr:resolve_route("create", {api: false})'
    inputs:
        enhavo_article.tag:
            extends: enhavo_taxonomy.term
            factory_arguments:
                - 'article_tag'
            permission: ROLE_ENHAVO_ARTICLE_TAG_INDEX
            actions:
                save:
                    type: save
                    permission: ROLE_ENHAVO_ARTICLE_TAG_CREATE
            actions_secondary:
                delete:
                    type: delete
                    enabled: expr:resource && resource.getId()
                    permission: ROLE_ENHAVO_ARTICLE_TAG_DELETE
