services:
    Enhavo\Bundle\AppBundle\Endpoint\Type\TemplateAdminEndpointType:
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }


    Enhavo\Bundle\AppBundle\Endpoint\Type\PreviewEndpointType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Input\InputFactory'
            - '@Enhavo\Component\Type\FactoryInterface[Endpoint]'
            - '@Enhavo\Bundle\ResourceBundle\ExpressionLanguage\ResourceExpressionLanguage'
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }

    Enhavo\Bundle\AppBundle\Endpoint\Type\AdminEndpointType:
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }

    Enhavo\Bundle\AppBundle\Endpoint\Type\AdminMainEndpointType:
        arguments:
            - '%enhavo_app.toolbar_widget.primary%'
            - '%enhavo_app.toolbar_widget.secondary%'
            - '@Enhavo\Bundle\AppBundle\Toolbar\ToolbarManager'
            - '%enhavo_app.branding%'
            - '%enhavo_app.menu%'
            - '@Enhavo\Bundle\AppBundle\Menu\MenuManager'
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }

    Enhavo\Bundle\AppBundle\Endpoint\Type\ModalFormEndpointType:
        arguments:
            - '@form.factory'
            - '@Enhavo\Bundle\VueFormBundle\Form\VueForm'
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }
