enhavo_translation:
    metadata:
        Enhavo\Bundle\TaxonomyBundle\Entity\Term:
            properties:
                name:
                    type: text
                text:
                    type: text