<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190521225230 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE user_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', firstName VARCHAR(255) DEFAULT NULL, lastName VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_F7129A8092FC23A8 (username_canonical), UNIQUE INDEX UNIQ_F7129A80A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_F7129A80C05FB297 (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_user_group (user_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_28657971A76ED395 (user_id), INDEX IDX_28657971FE54D947 (group_id), PRIMARY KEY(user_id, group_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', UNIQUE INDEX UNIQ_8F02BF9D5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media_usage (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media_format (id INT AUTO_INCREMENT NOT NULL, file_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, mimeType VARCHAR(255) DEFAULT NULL, extension VARCHAR(255) DEFAULT NULL, parameters LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', INDEX IDX_62C3E80193CB796C (file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media_file (id INT AUTO_INCREMENT NOT NULL, mimeType VARCHAR(255) DEFAULT NULL, extension VARCHAR(255) DEFAULT NULL, `order` INT DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, parameters LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', token VARCHAR(255) DEFAULT NULL, md5Checksum VARCHAR(255) DEFAULT NULL, library TINYINT(1) DEFAULT NULL, garbage TINYINT(1) NOT NULL, garbageTimestamp DATETIME DEFAULT NULL, createdAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_article (id INT AUTO_INCREMENT NOT NULL, route_id INT DEFAULT NULL, picture_id INT DEFAULT NULL, grid_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, metaDescription LONGTEXT DEFAULT NULL, pageTitle LONGTEXT DEFAULT NULL, public TINYINT(1) DEFAULT NULL, publicationDate DATETIME DEFAULT NULL, publishedUntil DATETIME DEFAULT NULL, priority DOUBLE PRECISION DEFAULT NULL, changeFrequency VARCHAR(255) DEFAULT NULL, noIndex TINYINT(1) DEFAULT NULL, noFollow TINYINT(1) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, openGraphTitle LONGTEXT DEFAULT NULL, openGraphDescription LONGTEXT DEFAULT NULL, teaser LONGTEXT DEFAULT NULL, openGraphImage_id INT DEFAULT NULL, INDEX IDX_EFE84AD134ECB4E6 (route_id), UNIQUE INDEX UNIQ_EFE84AD1EE45BDBF (picture_id), UNIQUE INDEX UNIQ_EFE84AD12CF16895 (grid_id), UNIQUE INDEX UNIQ_EFE84AD1BCC7F8A8 (openGraphImage_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_category (article_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_53A4EDAA7294869C (article_id), INDEX IDX_53A4EDAA12469DE2 (category_id), PRIMARY KEY(article_id, category_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page_page (id INT AUTO_INCREMENT NOT NULL, route_id INT DEFAULT NULL, grid_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, metaDescription LONGTEXT DEFAULT NULL, pageTitle LONGTEXT DEFAULT NULL, public TINYINT(1) DEFAULT NULL, publicationDate DATETIME DEFAULT NULL, publishedUntil DATETIME DEFAULT NULL, priority DOUBLE PRECISION DEFAULT NULL, changeFrequency VARCHAR(255) DEFAULT NULL, noIndex TINYINT(1) DEFAULT NULL, noFollow TINYINT(1) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, openGraphTitle LONGTEXT DEFAULT NULL, openGraphDescription LONGTEXT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, openGraphImage_id INT DEFAULT NULL, INDEX IDX_93CEAAFA34ECB4E6 (route_id), UNIQUE INDEX UNIQ_93CEAAFA2CF16895 (grid_id), INDEX IDX_93CEAAFA727ACA70 (parent_id), UNIQUE INDEX UNIQ_93CEAAFABCC7F8A8 (openGraphImage_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_collection (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_category (id INT AUTO_INCREMENT NOT NULL, picture_id INT DEFAULT NULL, collection_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, text LONGTEXT DEFAULT NULL, `order` INT DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_B1369DBAEE45BDBF (picture_id), INDEX IDX_B1369DBA514956FD (collection_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grid_grid (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grid_item (id INT AUTO_INCREMENT NOT NULL, grid_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, position INT DEFAULT NULL, itemTypeId INT DEFAULT NULL, itemTypeClass VARCHAR(255) DEFAULT NULL, INDEX IDX_3929884C2CF16895 (grid_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE slider_slider (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE slider_slide (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, slider_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, text LONGTEXT DEFAULT NULL, url TINYTEXT DEFAULT NULL, public TINYINT(1) DEFAULT NULL, publicationDate DATETIME DEFAULT NULL, publishedUntil DATETIME DEFAULT NULL, position INT DEFAULT NULL, UNIQUE INDEX UNIQ_F45BA2063DA5256D (image_id), INDEX IDX_F45BA2062CCC9638 (slider_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE setting_setting (id INT AUTO_INCREMENT NOT NULL, file_id INT DEFAULT NULL, `label` LONGTEXT DEFAULT NULL, `key` VARCHAR(255) DEFAULT NULL, type LONGTEXT DEFAULT NULL, value LONGTEXT DEFAULT NULL, date DATETIME DEFAULT NULL, translationDomain LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_C726087093CB796C (file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE setting_setting_files (setting_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_A6E69AE2EE35BD72 (setting_id), INDEX IDX_A6E69AE293CB796C (file_id), PRIMARY KEY(setting_id, file_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_subscriber (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(255) DEFAULT NULL, active TINYINT(1) DEFAULT NULL, activatedAt DATETIME DEFAULT NULL, createdAt DATETIME DEFAULT NULL, token VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_subscriber_group (subscriber_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_842BCA037808B1AD (subscriber_id), INDEX IDX_842BCA03FE54D947 (group_id), PRIMARY KEY(subscriber_id, group_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_newsletter (id INT AUTO_INCREMENT NOT NULL, grid_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, subject VARCHAR(255) DEFAULT NULL, sent TINYINT(1) DEFAULT \'0\', UNIQUE INDEX UNIQ_9390BC622CF16895 (grid_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter_group (id INT AUTO_INCREMENT NOT NULL, name LONGTEXT NOT NULL, code LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE calendar_appointment (id INT AUTO_INCREMENT NOT NULL, route_id INT DEFAULT NULL, grid_id INT DEFAULT NULL, picture_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, metaDescription LONGTEXT DEFAULT NULL, pageTitle LONGTEXT DEFAULT NULL, public TINYINT(1) DEFAULT NULL, publicationDate DATETIME DEFAULT NULL, publishedUntil DATETIME DEFAULT NULL, priority DOUBLE PRECISION DEFAULT NULL, changeFrequency VARCHAR(255) DEFAULT NULL, noIndex TINYINT(1) DEFAULT NULL, noFollow TINYINT(1) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, openGraphTitle LONGTEXT DEFAULT NULL, openGraphDescription LONGTEXT DEFAULT NULL, teaser LONGTEXT DEFAULT NULL, dateFrom DATETIME DEFAULT NULL, dateTo DATETIME DEFAULT NULL, externalId LONGTEXT DEFAULT NULL, locationLongitude LONGTEXT DEFAULT NULL, locationLatitude LONGTEXT DEFAULT NULL, locationName LONGTEXT DEFAULT NULL, locationCity LONGTEXT DEFAULT NULL, locationCountry LONGTEXT DEFAULT NULL, locationStreet LONGTEXT DEFAULT NULL, locationZip LONGTEXT DEFAULT NULL, repeatRule LONGTEXT DEFAULT NULL, importerName LONGTEXT DEFAULT NULL, notImporterHandled TINYINT(1) DEFAULT NULL, openGraphImage_id INT DEFAULT NULL, INDEX IDX_8EC4460F34ECB4E6 (route_id), UNIQUE INDEX UNIQ_8EC4460F2CF16895 (grid_id), UNIQUE INDEX UNIQ_8EC4460FEE45BDBF (picture_id), UNIQUE INDEX UNIQ_8EC4460FBCC7F8A8 (openGraphImage_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE content_redirect (id INT AUTO_INCREMENT NOT NULL, route_id INT DEFAULT NULL, `from` VARCHAR(512) DEFAULT NULL, `to` VARCHAR(512) DEFAULT NULL, code INT DEFAULT NULL, INDEX IDX_91BB74C434ECB4E6 (route_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE routing_route (id INT AUTO_INCREMENT NOT NULL, host VARCHAR(255) DEFAULT NULL, schemes LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', methods LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', defaults LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', requirements LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', options LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', condition_expr VARCHAR(255) DEFAULT NULL, variablePattern VARCHAR(255) DEFAULT NULL, staticPrefix VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, position INT DEFAULT NULL, contentClass VARCHAR(255) DEFAULT NULL, contentId INT DEFAULT NULL, INDEX name_idx (name), INDEX prefix_idx (staticPrefix), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE navigation_node (id INT AUTO_INCREMENT NOT NULL, navigation_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, `label` VARCHAR(255) DEFAULT NULL, position INT DEFAULT NULL, configuration LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', contentId INT DEFAULT NULL, contentClass VARCHAR(255) DEFAULT NULL, INDEX IDX_B2FF3D3739F79D6D (navigation_id), INDEX IDX_B2FF3D37727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE navigation_navigation (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE navigation_link (id INT AUTO_INCREMENT NOT NULL, link VARCHAR(1023) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_content (id INT AUTO_INCREMENT NOT NULL, magazine_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, teaser LONGTEXT DEFAULT NULL, tags LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', position INT DEFAULT NULL, INDEX IDX_68DB3CCC3EB84A1D (magazine_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_magazine (id INT AUTO_INCREMENT NOT NULL, cover_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, tags LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', INDEX IDX_AC2A43F922726E9 (cover_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_magazine_pictures (magazine_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_842A21113EB84A1D (magazine_id), INDEX IDX_842A211193CB796C (file_id), PRIMARY KEY(magazine_id, file_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE translation_translation_string (id INT AUTO_INCREMENT NOT NULL, translationKey VARCHAR(255) DEFAULT NULL, translationValue LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE translation_translation_route (id INT AUTO_INCREMENT NOT NULL, route_id INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, type VARCHAR(255) DEFAULT NULL, typeId INT DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, INDEX IDX_FDABACE634ECB4E6 (route_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE translation_translation (id INT AUTO_INCREMENT NOT NULL, class VARCHAR(255) NOT NULL, property VARCHAR(255) NOT NULL, refId INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, translation LONGTEXT DEFAULT NULL, INDEX IDX_REFERENCE (refId, class, property, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shop_voucher (id INT AUTO_INCREMENT NOT NULL, coupon_id INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, amount INT DEFAULT NULL, redeemAmount INT DEFAULT NULL, redeemedAt DATETIME DEFAULT NULL, createdAt DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_10A1E5F266C5951B (coupon_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shop_shipment (id INT AUTO_INCREMENT NOT NULL, method_id INT NOT NULL, state VARCHAR(255) NOT NULL, tracking VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_D973DA4A19883967 (method_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shop_product_association (id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shop_product (id INT AUTO_INCREMENT NOT NULL, picture_id INT DEFAULT NULL, route_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, enabled TINYINT(1) NOT NULL, title VARCHAR(255) NOT NULL, price INT DEFAULT NULL, height INT DEFAULT NULL, width INT DEFAULT NULL, depth INT DEFAULT NULL, volume INT DEFAULT NULL, weight INT DEFAULT NULL, taxRate_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_D079448777153098 (code), INDEX IDX_D0794487EE45BDBF (picture_id), INDEX IDX_D0794487C6CD2B2B (taxRate_id), INDEX IDX_D079448734ECB4E6 (route_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_options (product_id INT NOT NULL, option_id INT NOT NULL, INDEX IDX_2B5FF0094584665A (product_id), INDEX IDX_2B5FF009A7C41D6F (option_id), PRIMARY KEY(product_id, option_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shop_promotion (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, priority INT NOT NULL, exclusive TINYINT(1) NOT NULL, usage_limit INT DEFAULT NULL, used INT NOT NULL, coupon_based TINYINT(1) NOT NULL, starts_at DATETIME DEFAULT NULL, ends_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_D8AAF35A77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shop_user_address (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, differentBillingAddress TINYINT(1) DEFAULT NULL, shippingAddress_id INT DEFAULT NULL, billingAddress_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_48261619A76ED395 (user_id), INDEX IDX_48261619B1835C8F (shippingAddress_id), INDEX IDX_4826161943656FE6 (billingAddress_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shop_order (id INT AUTO_INCREMENT NOT NULL, shipment_id INT DEFAULT NULL, payment_id INT DEFAULT NULL, user_id INT DEFAULT NULL, number VARCHAR(255) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, state VARCHAR(255) NOT NULL, checkout_completed_at DATETIME DEFAULT NULL, items_total INT NOT NULL, adjustments_total INT NOT NULL, total INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, checkoutState VARCHAR(255) DEFAULT NULL, paymentState VARCHAR(255) DEFAULT NULL, shippingState VARCHAR(255) DEFAULT NULL, differentBillingAddress TINYINT(1) DEFAULT NULL, orderedAt DATETIME DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, token VARCHAR(255) DEFAULT NULL, trackingMail TINYINT(1) DEFAULT NULL, notice LONGTEXT DEFAULT NULL, shippingAddress_id INT DEFAULT NULL, billingAddress_id INT DEFAULT NULL, promotionCoupon_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_323FC9CA96901F54 (number), UNIQUE INDEX UNIQ_323FC9CA7BE036FC (shipment_id), INDEX IDX_323FC9CAB1835C8F (shippingAddress_id), INDEX IDX_323FC9CA43656FE6 (billingAddress_id), INDEX IDX_323FC9CACA0F69C (promotionCoupon_id), INDEX IDX_323FC9CA4C3A3BB (payment_id), INDEX IDX_323FC9CAA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shop_promotion_order (order_id INT NOT NULL, promotion_id INT NOT NULL, INDEX IDX_7CDCE3F18D9F6D38 (order_id), INDEX IDX_7CDCE3F1139DF194 (promotion_id), PRIMARY KEY(order_id, promotion_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shop_order_item (id INT AUTO_INCREMENT NOT NULL, order_id INT NOT NULL, product_id INT DEFAULT NULL, quantity INT NOT NULL, unit_price INT NOT NULL, units_total INT NOT NULL, adjustments_total INT NOT NULL, total INT NOT NULL, is_immutable TINYINT(1) NOT NULL, name VARCHAR(255) DEFAULT NULL, INDEX IDX_2899F22F8D9F6D38 (order_id), INDEX IDX_2899F22F4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE search_data_set (id INT AUTO_INCREMENT NOT NULL, contentId INT DEFAULT NULL, contentClass VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE search_filter (id INT AUTO_INCREMENT NOT NULL, `key` VARCHAR(255) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, dataSet_id INT DEFAULT NULL, INDEX IDX_A6263002D3D0282D (dataSet_id), INDEX key_idx (`key`), INDEX value_idx (value), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE search_total (id INT AUTO_INCREMENT NOT NULL, word VARCHAR(255) NOT NULL, count DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE search_index (id INT AUTO_INCREMENT NOT NULL, word VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) DEFAULT NULL, weight INT DEFAULT NULL, score DOUBLE PRECISION DEFAULT NULL, dataSet_id INT DEFAULT NULL, INDEX IDX_B446A4E8D3D0282D (dataSet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grid_item_text_picture (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, file_id INT DEFAULT NULL, text LONGTEXT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, caption VARCHAR(255) DEFAULT NULL, textLeft TINYINT(1) DEFAULT NULL, `float` TINYINT(1) DEFAULT NULL, layout INT DEFAULT NULL, INDEX IDX_40EA2BF1126F525E (item_id), UNIQUE INDEX UNIQ_40EA2BF193CB796C (file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grid_item_video (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, INDEX IDX_F973395F126F525E (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grid_item_cite (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, text LONGTEXT DEFAULT NULL, INDEX IDX_E889F529126F525E (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grid_item_picture (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, file_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, caption VARCHAR(255) DEFAULT NULL, INDEX IDX_2BCA53CA126F525E (item_id), UNIQUE INDEX UNIQ_2BCA53CA93CB796C (file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grid_item_gallery (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, text LONGTEXT DEFAULT NULL, INDEX IDX_7A3A6479126F525E (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grid_item_gallery_file (gallery_id INT NOT NULL, file_id INT NOT NULL, INDEX IDX_6D1055DB4E7AF8F (gallery_id), INDEX IDX_6D1055DB93CB796C (file_id), PRIMARY KEY(gallery_id, file_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grid_item_text (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, text LONGTEXT DEFAULT NULL, INDEX IDX_EA580C95126F525E (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grid_item_two_column (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, width VARCHAR(255) DEFAULT NULL, style VARCHAR(255) DEFAULT NULL, columnOne_id INT DEFAULT NULL, columnTwo_id INT DEFAULT NULL, INDEX IDX_6636A017126F525E (item_id), INDEX IDX_6636A0174B499059 (columnOne_id), INDEX IDX_6636A01720157796 (columnTwo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grid_item_three_column (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, width VARCHAR(255) DEFAULT NULL, style VARCHAR(255) DEFAULT NULL, columnOne_id INT DEFAULT NULL, columnTwo_id INT DEFAULT NULL, columnThree_id INT DEFAULT NULL, INDEX IDX_A151C0CC126F525E (item_id), INDEX IDX_A151C0CC4B499059 (columnOne_id), INDEX IDX_A151C0CC20157796 (columnTwo_id), INDEX IDX_A151C0CCF1E466CA (columnThree_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grid_item_one_column (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, column_id INT DEFAULT NULL, width VARCHAR(255) DEFAULT NULL, style VARCHAR(255) DEFAULT NULL, INDEX IDX_28DB32EA126F525E (item_id), INDEX IDX_28DB32EABE8E8ED5 (column_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_payment_method_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, instructions LONGTEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_966BE3A12C2AC5D3 (translatable_id), UNIQUE INDEX sylius_payment_method_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_payment_method (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, environment VARCHAR(255) DEFAULT NULL, is_enabled TINYINT(1) NOT NULL, position INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_A75B0B0D77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_payment (id INT AUTO_INCREMENT NOT NULL, method_id INT DEFAULT NULL, currency_code VARCHAR(3) NOT NULL, amount INT NOT NULL, state VARCHAR(255) NOT NULL, details LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_D9191BD419883967 (method_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_order_sequence (id INT AUTO_INCREMENT NOT NULL, idx INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_order_item_unit (id INT AUTO_INCREMENT NOT NULL, order_item_id INT NOT NULL, adjustments_total INT NOT NULL, INDEX IDX_82BF226EE415FB15 (order_item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_adjustment (id INT AUTO_INCREMENT NOT NULL, order_id INT DEFAULT NULL, order_item_id INT DEFAULT NULL, order_item_unit_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, `label` VARCHAR(255) DEFAULT NULL, amount INT NOT NULL, is_neutral TINYINT(1) NOT NULL, is_locked TINYINT(1) NOT NULL, origin_code VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_ACA6E0F28D9F6D38 (order_id), INDEX IDX_ACA6E0F2E415FB15 (order_item_id), INDEX IDX_ACA6E0F2F720C233 (order_item_unit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_promotion_coupon (id INT AUTO_INCREMENT NOT NULL, promotion_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, usage_limit INT DEFAULT NULL, used INT NOT NULL, expires_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_B04EBA8577153098 (code), INDEX IDX_B04EBA85139DF194 (promotion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_promotion_action (id INT AUTO_INCREMENT NOT NULL, promotion_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, configuration LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', INDEX IDX_933D0915139DF194 (promotion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_promotion_rule (id INT AUTO_INCREMENT NOT NULL, promotion_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, configuration LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', INDEX IDX_2C188EA8139DF194 (promotion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_shipping_method_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_2B37DB3D2C2AC5D3 (translatable_id), UNIQUE INDEX sylius_shipping_method_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_shipping_method (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, configuration LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', category_requirement INT NOT NULL, calculator VARCHAR(255) NOT NULL, is_enabled TINYINT(1) NOT NULL, position INT NOT NULL, archived_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_5FB0EE1177153098 (code), INDEX IDX_5FB0EE1112469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_shipping_category (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_B1D6465277153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_shipment_unit (id INT AUTO_INCREMENT NOT NULL, shipment_id INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_2EC26E237BE036FC (shipment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_locale (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(12) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_7BA1286477153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_option (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, position INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_E4C0EBEF77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_option_value_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, value VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_8D4382DC2C2AC5D3 (translatable_id), UNIQUE INDEX sylius_product_option_value_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_association_type (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_CCB8914C77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, meta_keywords VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_105A9082C2AC5D3 (translatable_id), UNIQUE INDEX UNIQ_105A9084180C698989D9B62 (locale, slug), UNIQUE INDEX sylius_product_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_variant (id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, code VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, position INT NOT NULL, UNIQUE INDEX UNIQ_A29B52377153098 (code), INDEX IDX_A29B5234584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_variant_option_value (variant_id INT NOT NULL, option_value_id INT NOT NULL, INDEX IDX_76CDAFA13B69A9AF (variant_id), INDEX IDX_76CDAFA1D957CA06 (option_value_id), PRIMARY KEY(variant_id, option_value_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_variant_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_8DC18EDC2C2AC5D3 (translatable_id), UNIQUE INDEX sylius_product_variant_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_option_value (id INT AUTO_INCREMENT NOT NULL, option_id INT NOT NULL, code VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_F7FF7D4B77153098 (code), INDEX IDX_F7FF7D4BA7C41D6F (option_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_association_type_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_4F618E52C2AC5D3 (translatable_id), UNIQUE INDEX sylius_product_association_type_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_option_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_CBA491AD2C2AC5D3 (translatable_id), UNIQUE INDEX sylius_product_option_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_attribute (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, storage_type VARCHAR(255) NOT NULL, configuration LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, position INT NOT NULL, UNIQUE INDEX UNIQ_BFAF484A77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_association (id INT AUTO_INCREMENT NOT NULL, association_type_id INT NOT NULL, product_id INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_48E9CDABB1E1C39 (association_type_id), INDEX IDX_48E9CDAB4584665A (product_id), UNIQUE INDEX product_association_idx (product_id, association_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_association_product (association_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_A427B983EFB9C8A5 (association_id), INDEX IDX_A427B9834584665A (product_id), PRIMARY KEY(association_id, product_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_attribute_value (id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, attribute_id INT NOT NULL, locale_code VARCHAR(255) NOT NULL, text_value LONGTEXT DEFAULT NULL, boolean_value TINYINT(1) DEFAULT NULL, integer_value INT DEFAULT NULL, float_value DOUBLE PRECISION DEFAULT NULL, datetime_value DATETIME DEFAULT NULL, date_value DATE DEFAULT NULL, json_value LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', INDEX IDX_8A053E544584665A (product_id), INDEX IDX_8A053E54B6E62EFA (attribute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_attribute_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_93850EBA2C2AC5D3 (translatable_id), UNIQUE INDEX sylius_product_attribute_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_province (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, abbreviation VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_B5618FE477153098 (code), INDEX IDX_B5618FE4F92F3E70 (country_id), UNIQUE INDEX UNIQ_B5618FE4F92F3E705E237E06 (country_id, name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_address (id INT AUTO_INCREMENT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, phone_number VARCHAR(255) DEFAULT NULL, street VARCHAR(255) NOT NULL, company VARCHAR(255) DEFAULT NULL, city VARCHAR(255) NOT NULL, postcode VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, country_code VARCHAR(255) NOT NULL, province_code VARCHAR(255) DEFAULT NULL, province_name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_zone_member (id INT AUTO_INCREMENT NOT NULL, belongs_to INT DEFAULT NULL, code VARCHAR(255) NOT NULL, INDEX IDX_E8B5ABF34B0E929B (belongs_to), UNIQUE INDEX UNIQ_E8B5ABF34B0E929B77153098 (belongs_to, code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_country (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(2) NOT NULL, enabled TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_E74256BF77153098 (code), INDEX IDX_E74256BF77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_address_log_entries (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(255) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', username VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_zone (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(8) NOT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_7BE2258E77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_currency (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(3) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_96EDD3D077153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_exchange_rate (id INT AUTO_INCREMENT NOT NULL, source_currency INT NOT NULL, target_currency INT NOT NULL, ratio NUMERIC(10, 5) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_5F52B852A76BEED (source_currency), INDEX IDX_5F52B85B3FD5856 (target_currency), UNIQUE INDEX UNIQ_5F52B852A76BEEDB3FD5856 (source_currency, target_currency), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_inventory_unit (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_tax_rate (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, amount NUMERIC(10, 5) NOT NULL, included_in_price TINYINT(1) NOT NULL, calculator VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_3CD86B2E77153098 (code), INDEX IDX_3CD86B2E12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_tax_category (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_221EB0BE77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE user_user_group ADD CONSTRAINT FK_28657971A76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_user_group ADD CONSTRAINT FK_28657971FE54D947 FOREIGN KEY (group_id) REFERENCES user_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE media_format ADD CONSTRAINT FK_62C3E80193CB796C FOREIGN KEY (file_id) REFERENCES media_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_article ADD CONSTRAINT FK_EFE84AD134ECB4E6 FOREIGN KEY (route_id) REFERENCES routing_route (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_article ADD CONSTRAINT FK_EFE84AD1EE45BDBF FOREIGN KEY (picture_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE article_article ADD CONSTRAINT FK_EFE84AD12CF16895 FOREIGN KEY (grid_id) REFERENCES grid_grid (id)');
        $this->addSql('ALTER TABLE article_article ADD CONSTRAINT FK_EFE84AD1BCC7F8A8 FOREIGN KEY (openGraphImage_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE article_category ADD CONSTRAINT FK_53A4EDAA7294869C FOREIGN KEY (article_id) REFERENCES article_article (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_category ADD CONSTRAINT FK_53A4EDAA12469DE2 FOREIGN KEY (category_id) REFERENCES category_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE page_page ADD CONSTRAINT FK_93CEAAFA34ECB4E6 FOREIGN KEY (route_id) REFERENCES routing_route (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE page_page ADD CONSTRAINT FK_93CEAAFA2CF16895 FOREIGN KEY (grid_id) REFERENCES grid_grid (id)');
        $this->addSql('ALTER TABLE page_page ADD CONSTRAINT FK_93CEAAFA727ACA70 FOREIGN KEY (parent_id) REFERENCES page_page (id)');
        $this->addSql('ALTER TABLE page_page ADD CONSTRAINT FK_93CEAAFABCC7F8A8 FOREIGN KEY (openGraphImage_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE category_category ADD CONSTRAINT FK_B1369DBAEE45BDBF FOREIGN KEY (picture_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE category_category ADD CONSTRAINT FK_B1369DBA514956FD FOREIGN KEY (collection_id) REFERENCES category_collection (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item ADD CONSTRAINT FK_3929884C2CF16895 FOREIGN KEY (grid_id) REFERENCES grid_grid (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE slider_slide ADD CONSTRAINT FK_F45BA2063DA5256D FOREIGN KEY (image_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE slider_slide ADD CONSTRAINT FK_F45BA2062CCC9638 FOREIGN KEY (slider_id) REFERENCES slider_slider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE setting_setting ADD CONSTRAINT FK_C726087093CB796C FOREIGN KEY (file_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE setting_setting_files ADD CONSTRAINT FK_A6E69AE2EE35BD72 FOREIGN KEY (setting_id) REFERENCES setting_setting (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE setting_setting_files ADD CONSTRAINT FK_A6E69AE293CB796C FOREIGN KEY (file_id) REFERENCES media_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE newsletter_subscriber_group ADD CONSTRAINT FK_842BCA037808B1AD FOREIGN KEY (subscriber_id) REFERENCES newsletter_subscriber (id)');
        $this->addSql('ALTER TABLE newsletter_subscriber_group ADD CONSTRAINT FK_842BCA03FE54D947 FOREIGN KEY (group_id) REFERENCES newsletter_group (id)');
        $this->addSql('ALTER TABLE newsletter_newsletter ADD CONSTRAINT FK_9390BC622CF16895 FOREIGN KEY (grid_id) REFERENCES grid_grid (id)');
        $this->addSql('ALTER TABLE calendar_appointment ADD CONSTRAINT FK_8EC4460F34ECB4E6 FOREIGN KEY (route_id) REFERENCES routing_route (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE calendar_appointment ADD CONSTRAINT FK_8EC4460F2CF16895 FOREIGN KEY (grid_id) REFERENCES grid_grid (id)');
        $this->addSql('ALTER TABLE calendar_appointment ADD CONSTRAINT FK_8EC4460FEE45BDBF FOREIGN KEY (picture_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE calendar_appointment ADD CONSTRAINT FK_8EC4460FBCC7F8A8 FOREIGN KEY (openGraphImage_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE content_redirect ADD CONSTRAINT FK_91BB74C434ECB4E6 FOREIGN KEY (route_id) REFERENCES routing_route (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE navigation_node ADD CONSTRAINT FK_B2FF3D3739F79D6D FOREIGN KEY (navigation_id) REFERENCES navigation_navigation (id)');
        $this->addSql('ALTER TABLE navigation_node ADD CONSTRAINT FK_B2FF3D37727ACA70 FOREIGN KEY (parent_id) REFERENCES navigation_node (id)');
        $this->addSql('ALTER TABLE project_content ADD CONSTRAINT FK_68DB3CCC3EB84A1D FOREIGN KEY (magazine_id) REFERENCES project_magazine (id)');
        $this->addSql('ALTER TABLE project_magazine ADD CONSTRAINT FK_AC2A43F922726E9 FOREIGN KEY (cover_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE project_magazine_pictures ADD CONSTRAINT FK_842A21113EB84A1D FOREIGN KEY (magazine_id) REFERENCES project_magazine (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_magazine_pictures ADD CONSTRAINT FK_842A211193CB796C FOREIGN KEY (file_id) REFERENCES media_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE translation_translation_route ADD CONSTRAINT FK_FDABACE634ECB4E6 FOREIGN KEY (route_id) REFERENCES routing_route (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shop_voucher ADD CONSTRAINT FK_10A1E5F266C5951B FOREIGN KEY (coupon_id) REFERENCES sylius_promotion_coupon (id)');
        $this->addSql('ALTER TABLE shop_shipment ADD CONSTRAINT FK_D973DA4A19883967 FOREIGN KEY (method_id) REFERENCES sylius_shipping_method (id)');
        $this->addSql('ALTER TABLE shop_product ADD CONSTRAINT FK_D0794487EE45BDBF FOREIGN KEY (picture_id) REFERENCES media_file (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shop_product ADD CONSTRAINT FK_D0794487C6CD2B2B FOREIGN KEY (taxRate_id) REFERENCES sylius_tax_rate (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shop_product ADD CONSTRAINT FK_D079448734ECB4E6 FOREIGN KEY (route_id) REFERENCES routing_route (id)');
        $this->addSql('ALTER TABLE sylius_product_options ADD CONSTRAINT FK_2B5FF0094584665A FOREIGN KEY (product_id) REFERENCES shop_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_options ADD CONSTRAINT FK_2B5FF009A7C41D6F FOREIGN KEY (option_id) REFERENCES sylius_product_option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shop_user_address ADD CONSTRAINT FK_48261619A76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id)');
        $this->addSql('ALTER TABLE shop_user_address ADD CONSTRAINT FK_48261619B1835C8F FOREIGN KEY (shippingAddress_id) REFERENCES sylius_address (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shop_user_address ADD CONSTRAINT FK_4826161943656FE6 FOREIGN KEY (billingAddress_id) REFERENCES sylius_address (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shop_order ADD CONSTRAINT FK_323FC9CA7BE036FC FOREIGN KEY (shipment_id) REFERENCES shop_shipment (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shop_order ADD CONSTRAINT FK_323FC9CAB1835C8F FOREIGN KEY (shippingAddress_id) REFERENCES sylius_address (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shop_order ADD CONSTRAINT FK_323FC9CA43656FE6 FOREIGN KEY (billingAddress_id) REFERENCES sylius_address (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shop_order ADD CONSTRAINT FK_323FC9CACA0F69C FOREIGN KEY (promotionCoupon_id) REFERENCES sylius_promotion_coupon (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shop_order ADD CONSTRAINT FK_323FC9CA4C3A3BB FOREIGN KEY (payment_id) REFERENCES sylius_payment (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shop_order ADD CONSTRAINT FK_323FC9CAA76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shop_promotion_order ADD CONSTRAINT FK_7CDCE3F18D9F6D38 FOREIGN KEY (order_id) REFERENCES shop_order (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shop_promotion_order ADD CONSTRAINT FK_7CDCE3F1139DF194 FOREIGN KEY (promotion_id) REFERENCES shop_promotion (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shop_order_item ADD CONSTRAINT FK_2899F22F8D9F6D38 FOREIGN KEY (order_id) REFERENCES shop_order (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shop_order_item ADD CONSTRAINT FK_2899F22F4584665A FOREIGN KEY (product_id) REFERENCES shop_product (id)');
        $this->addSql('ALTER TABLE search_filter ADD CONSTRAINT FK_A6263002D3D0282D FOREIGN KEY (dataSet_id) REFERENCES search_data_set (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE search_index ADD CONSTRAINT FK_B446A4E8D3D0282D FOREIGN KEY (dataSet_id) REFERENCES search_data_set (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_text_picture ADD CONSTRAINT FK_40EA2BF1126F525E FOREIGN KEY (item_id) REFERENCES grid_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_text_picture ADD CONSTRAINT FK_40EA2BF193CB796C FOREIGN KEY (file_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE grid_item_video ADD CONSTRAINT FK_F973395F126F525E FOREIGN KEY (item_id) REFERENCES grid_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_cite ADD CONSTRAINT FK_E889F529126F525E FOREIGN KEY (item_id) REFERENCES grid_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_picture ADD CONSTRAINT FK_2BCA53CA126F525E FOREIGN KEY (item_id) REFERENCES grid_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_picture ADD CONSTRAINT FK_2BCA53CA93CB796C FOREIGN KEY (file_id) REFERENCES media_file (id)');
        $this->addSql('ALTER TABLE grid_item_gallery ADD CONSTRAINT FK_7A3A6479126F525E FOREIGN KEY (item_id) REFERENCES grid_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_gallery_file ADD CONSTRAINT FK_6D1055DB4E7AF8F FOREIGN KEY (gallery_id) REFERENCES grid_item_gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_gallery_file ADD CONSTRAINT FK_6D1055DB93CB796C FOREIGN KEY (file_id) REFERENCES media_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_text ADD CONSTRAINT FK_EA580C95126F525E FOREIGN KEY (item_id) REFERENCES grid_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_two_column ADD CONSTRAINT FK_6636A017126F525E FOREIGN KEY (item_id) REFERENCES grid_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_two_column ADD CONSTRAINT FK_6636A0174B499059 FOREIGN KEY (columnOne_id) REFERENCES grid_grid (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_two_column ADD CONSTRAINT FK_6636A01720157796 FOREIGN KEY (columnTwo_id) REFERENCES grid_grid (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_three_column ADD CONSTRAINT FK_A151C0CC126F525E FOREIGN KEY (item_id) REFERENCES grid_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_three_column ADD CONSTRAINT FK_A151C0CC4B499059 FOREIGN KEY (columnOne_id) REFERENCES grid_grid (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_three_column ADD CONSTRAINT FK_A151C0CC20157796 FOREIGN KEY (columnTwo_id) REFERENCES grid_grid (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_three_column ADD CONSTRAINT FK_A151C0CCF1E466CA FOREIGN KEY (columnThree_id) REFERENCES grid_grid (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_one_column ADD CONSTRAINT FK_28DB32EA126F525E FOREIGN KEY (item_id) REFERENCES grid_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grid_item_one_column ADD CONSTRAINT FK_28DB32EABE8E8ED5 FOREIGN KEY (column_id) REFERENCES grid_grid (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_payment_method_translation ADD CONSTRAINT FK_966BE3A12C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_payment_method (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_payment ADD CONSTRAINT FK_D9191BD419883967 FOREIGN KEY (method_id) REFERENCES sylius_payment_method (id)');
        $this->addSql('ALTER TABLE sylius_order_item_unit ADD CONSTRAINT FK_82BF226EE415FB15 FOREIGN KEY (order_item_id) REFERENCES shop_order_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_adjustment ADD CONSTRAINT FK_ACA6E0F28D9F6D38 FOREIGN KEY (order_id) REFERENCES shop_order (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_adjustment ADD CONSTRAINT FK_ACA6E0F2E415FB15 FOREIGN KEY (order_item_id) REFERENCES shop_order_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_adjustment ADD CONSTRAINT FK_ACA6E0F2F720C233 FOREIGN KEY (order_item_unit_id) REFERENCES sylius_order_item_unit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_promotion_coupon ADD CONSTRAINT FK_B04EBA85139DF194 FOREIGN KEY (promotion_id) REFERENCES shop_promotion (id)');
        $this->addSql('ALTER TABLE sylius_promotion_action ADD CONSTRAINT FK_933D0915139DF194 FOREIGN KEY (promotion_id) REFERENCES shop_promotion (id)');
        $this->addSql('ALTER TABLE sylius_promotion_rule ADD CONSTRAINT FK_2C188EA8139DF194 FOREIGN KEY (promotion_id) REFERENCES shop_promotion (id)');
        $this->addSql('ALTER TABLE sylius_shipping_method_translation ADD CONSTRAINT FK_2B37DB3D2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_shipping_method (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_shipping_method ADD CONSTRAINT FK_5FB0EE1112469DE2 FOREIGN KEY (category_id) REFERENCES sylius_shipping_category (id)');
        $this->addSql('ALTER TABLE sylius_shipment_unit ADD CONSTRAINT FK_2EC26E237BE036FC FOREIGN KEY (shipment_id) REFERENCES shop_shipment (id)');
        $this->addSql('ALTER TABLE sylius_product_option_value_translation ADD CONSTRAINT FK_8D4382DC2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_option_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_translation ADD CONSTRAINT FK_105A9082C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES shop_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_variant ADD CONSTRAINT FK_A29B5234584665A FOREIGN KEY (product_id) REFERENCES shop_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_variant_option_value ADD CONSTRAINT FK_76CDAFA13B69A9AF FOREIGN KEY (variant_id) REFERENCES sylius_product_variant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_variant_option_value ADD CONSTRAINT FK_76CDAFA1D957CA06 FOREIGN KEY (option_value_id) REFERENCES sylius_product_option_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_variant_translation ADD CONSTRAINT FK_8DC18EDC2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_variant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_option_value ADD CONSTRAINT FK_F7FF7D4BA7C41D6F FOREIGN KEY (option_id) REFERENCES sylius_product_option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_association_type_translation ADD CONSTRAINT FK_4F618E52C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_association_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_option_translation ADD CONSTRAINT FK_CBA491AD2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_association ADD CONSTRAINT FK_48E9CDABB1E1C39 FOREIGN KEY (association_type_id) REFERENCES sylius_product_association_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_association ADD CONSTRAINT FK_48E9CDAB4584665A FOREIGN KEY (product_id) REFERENCES shop_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_association_product ADD CONSTRAINT FK_A427B983EFB9C8A5 FOREIGN KEY (association_id) REFERENCES sylius_product_association (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_association_product ADD CONSTRAINT FK_A427B9834584665A FOREIGN KEY (product_id) REFERENCES shop_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_attribute_value ADD CONSTRAINT FK_8A053E544584665A FOREIGN KEY (product_id) REFERENCES shop_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_attribute_value ADD CONSTRAINT FK_8A053E54B6E62EFA FOREIGN KEY (attribute_id) REFERENCES sylius_product_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_attribute_translation ADD CONSTRAINT FK_93850EBA2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_province ADD CONSTRAINT FK_B5618FE4F92F3E70 FOREIGN KEY (country_id) REFERENCES sylius_country (id)');
        $this->addSql('ALTER TABLE sylius_zone_member ADD CONSTRAINT FK_E8B5ABF34B0E929B FOREIGN KEY (belongs_to) REFERENCES sylius_zone (id)');
        $this->addSql('ALTER TABLE sylius_exchange_rate ADD CONSTRAINT FK_5F52B852A76BEED FOREIGN KEY (source_currency) REFERENCES sylius_currency (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_exchange_rate ADD CONSTRAINT FK_5F52B85B3FD5856 FOREIGN KEY (target_currency) REFERENCES sylius_currency (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_tax_rate ADD CONSTRAINT FK_3CD86B2E12469DE2 FOREIGN KEY (category_id) REFERENCES sylius_tax_category (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE user_user_group DROP FOREIGN KEY FK_28657971A76ED395');
        $this->addSql('ALTER TABLE shop_user_address DROP FOREIGN KEY FK_48261619A76ED395');
        $this->addSql('ALTER TABLE shop_order DROP FOREIGN KEY FK_323FC9CAA76ED395');
        $this->addSql('ALTER TABLE user_user_group DROP FOREIGN KEY FK_28657971FE54D947');
        $this->addSql('ALTER TABLE media_format DROP FOREIGN KEY FK_62C3E80193CB796C');
        $this->addSql('ALTER TABLE article_article DROP FOREIGN KEY FK_EFE84AD1EE45BDBF');
        $this->addSql('ALTER TABLE article_article DROP FOREIGN KEY FK_EFE84AD1BCC7F8A8');
        $this->addSql('ALTER TABLE page_page DROP FOREIGN KEY FK_93CEAAFABCC7F8A8');
        $this->addSql('ALTER TABLE category_category DROP FOREIGN KEY FK_B1369DBAEE45BDBF');
        $this->addSql('ALTER TABLE slider_slide DROP FOREIGN KEY FK_F45BA2063DA5256D');
        $this->addSql('ALTER TABLE setting_setting DROP FOREIGN KEY FK_C726087093CB796C');
        $this->addSql('ALTER TABLE setting_setting_files DROP FOREIGN KEY FK_A6E69AE293CB796C');
        $this->addSql('ALTER TABLE calendar_appointment DROP FOREIGN KEY FK_8EC4460FEE45BDBF');
        $this->addSql('ALTER TABLE calendar_appointment DROP FOREIGN KEY FK_8EC4460FBCC7F8A8');
        $this->addSql('ALTER TABLE project_magazine DROP FOREIGN KEY FK_AC2A43F922726E9');
        $this->addSql('ALTER TABLE project_magazine_pictures DROP FOREIGN KEY FK_842A211193CB796C');
        $this->addSql('ALTER TABLE shop_product DROP FOREIGN KEY FK_D0794487EE45BDBF');
        $this->addSql('ALTER TABLE grid_item_text_picture DROP FOREIGN KEY FK_40EA2BF193CB796C');
        $this->addSql('ALTER TABLE grid_item_picture DROP FOREIGN KEY FK_2BCA53CA93CB796C');
        $this->addSql('ALTER TABLE grid_item_gallery_file DROP FOREIGN KEY FK_6D1055DB93CB796C');
        $this->addSql('ALTER TABLE article_category DROP FOREIGN KEY FK_53A4EDAA7294869C');
        $this->addSql('ALTER TABLE page_page DROP FOREIGN KEY FK_93CEAAFA727ACA70');
        $this->addSql('ALTER TABLE category_category DROP FOREIGN KEY FK_B1369DBA514956FD');
        $this->addSql('ALTER TABLE article_category DROP FOREIGN KEY FK_53A4EDAA12469DE2');
        $this->addSql('ALTER TABLE article_article DROP FOREIGN KEY FK_EFE84AD12CF16895');
        $this->addSql('ALTER TABLE page_page DROP FOREIGN KEY FK_93CEAAFA2CF16895');
        $this->addSql('ALTER TABLE grid_item DROP FOREIGN KEY FK_3929884C2CF16895');
        $this->addSql('ALTER TABLE newsletter_newsletter DROP FOREIGN KEY FK_9390BC622CF16895');
        $this->addSql('ALTER TABLE calendar_appointment DROP FOREIGN KEY FK_8EC4460F2CF16895');
        $this->addSql('ALTER TABLE grid_item_two_column DROP FOREIGN KEY FK_6636A0174B499059');
        $this->addSql('ALTER TABLE grid_item_two_column DROP FOREIGN KEY FK_6636A01720157796');
        $this->addSql('ALTER TABLE grid_item_three_column DROP FOREIGN KEY FK_A151C0CC4B499059');
        $this->addSql('ALTER TABLE grid_item_three_column DROP FOREIGN KEY FK_A151C0CC20157796');
        $this->addSql('ALTER TABLE grid_item_three_column DROP FOREIGN KEY FK_A151C0CCF1E466CA');
        $this->addSql('ALTER TABLE grid_item_one_column DROP FOREIGN KEY FK_28DB32EABE8E8ED5');
        $this->addSql('ALTER TABLE grid_item_text_picture DROP FOREIGN KEY FK_40EA2BF1126F525E');
        $this->addSql('ALTER TABLE grid_item_video DROP FOREIGN KEY FK_F973395F126F525E');
        $this->addSql('ALTER TABLE grid_item_cite DROP FOREIGN KEY FK_E889F529126F525E');
        $this->addSql('ALTER TABLE grid_item_picture DROP FOREIGN KEY FK_2BCA53CA126F525E');
        $this->addSql('ALTER TABLE grid_item_gallery DROP FOREIGN KEY FK_7A3A6479126F525E');
        $this->addSql('ALTER TABLE grid_item_text DROP FOREIGN KEY FK_EA580C95126F525E');
        $this->addSql('ALTER TABLE grid_item_two_column DROP FOREIGN KEY FK_6636A017126F525E');
        $this->addSql('ALTER TABLE grid_item_three_column DROP FOREIGN KEY FK_A151C0CC126F525E');
        $this->addSql('ALTER TABLE grid_item_one_column DROP FOREIGN KEY FK_28DB32EA126F525E');
        $this->addSql('ALTER TABLE slider_slide DROP FOREIGN KEY FK_F45BA2062CCC9638');
        $this->addSql('ALTER TABLE setting_setting_files DROP FOREIGN KEY FK_A6E69AE2EE35BD72');
        $this->addSql('ALTER TABLE newsletter_subscriber_group DROP FOREIGN KEY FK_842BCA037808B1AD');
        $this->addSql('ALTER TABLE newsletter_subscriber_group DROP FOREIGN KEY FK_842BCA03FE54D947');
        $this->addSql('ALTER TABLE article_article DROP FOREIGN KEY FK_EFE84AD134ECB4E6');
        $this->addSql('ALTER TABLE page_page DROP FOREIGN KEY FK_93CEAAFA34ECB4E6');
        $this->addSql('ALTER TABLE calendar_appointment DROP FOREIGN KEY FK_8EC4460F34ECB4E6');
        $this->addSql('ALTER TABLE content_redirect DROP FOREIGN KEY FK_91BB74C434ECB4E6');
        $this->addSql('ALTER TABLE translation_translation_route DROP FOREIGN KEY FK_FDABACE634ECB4E6');
        $this->addSql('ALTER TABLE shop_product DROP FOREIGN KEY FK_D079448734ECB4E6');
        $this->addSql('ALTER TABLE navigation_node DROP FOREIGN KEY FK_B2FF3D37727ACA70');
        $this->addSql('ALTER TABLE navigation_node DROP FOREIGN KEY FK_B2FF3D3739F79D6D');
        $this->addSql('ALTER TABLE project_content DROP FOREIGN KEY FK_68DB3CCC3EB84A1D');
        $this->addSql('ALTER TABLE project_magazine_pictures DROP FOREIGN KEY FK_842A21113EB84A1D');
        $this->addSql('ALTER TABLE shop_order DROP FOREIGN KEY FK_323FC9CA7BE036FC');
        $this->addSql('ALTER TABLE sylius_shipment_unit DROP FOREIGN KEY FK_2EC26E237BE036FC');
        $this->addSql('ALTER TABLE sylius_product_options DROP FOREIGN KEY FK_2B5FF0094584665A');
        $this->addSql('ALTER TABLE shop_order_item DROP FOREIGN KEY FK_2899F22F4584665A');
        $this->addSql('ALTER TABLE sylius_product_translation DROP FOREIGN KEY FK_105A9082C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_variant DROP FOREIGN KEY FK_A29B5234584665A');
        $this->addSql('ALTER TABLE sylius_product_association DROP FOREIGN KEY FK_48E9CDAB4584665A');
        $this->addSql('ALTER TABLE sylius_product_association_product DROP FOREIGN KEY FK_A427B9834584665A');
        $this->addSql('ALTER TABLE sylius_product_attribute_value DROP FOREIGN KEY FK_8A053E544584665A');
        $this->addSql('ALTER TABLE shop_promotion_order DROP FOREIGN KEY FK_7CDCE3F1139DF194');
        $this->addSql('ALTER TABLE sylius_promotion_coupon DROP FOREIGN KEY FK_B04EBA85139DF194');
        $this->addSql('ALTER TABLE sylius_promotion_action DROP FOREIGN KEY FK_933D0915139DF194');
        $this->addSql('ALTER TABLE sylius_promotion_rule DROP FOREIGN KEY FK_2C188EA8139DF194');
        $this->addSql('ALTER TABLE shop_promotion_order DROP FOREIGN KEY FK_7CDCE3F18D9F6D38');
        $this->addSql('ALTER TABLE shop_order_item DROP FOREIGN KEY FK_2899F22F8D9F6D38');
        $this->addSql('ALTER TABLE sylius_adjustment DROP FOREIGN KEY FK_ACA6E0F28D9F6D38');
        $this->addSql('ALTER TABLE sylius_order_item_unit DROP FOREIGN KEY FK_82BF226EE415FB15');
        $this->addSql('ALTER TABLE sylius_adjustment DROP FOREIGN KEY FK_ACA6E0F2E415FB15');
        $this->addSql('ALTER TABLE search_filter DROP FOREIGN KEY FK_A6263002D3D0282D');
        $this->addSql('ALTER TABLE search_index DROP FOREIGN KEY FK_B446A4E8D3D0282D');
        $this->addSql('ALTER TABLE grid_item_gallery_file DROP FOREIGN KEY FK_6D1055DB4E7AF8F');
        $this->addSql('ALTER TABLE sylius_payment_method_translation DROP FOREIGN KEY FK_966BE3A12C2AC5D3');
        $this->addSql('ALTER TABLE sylius_payment DROP FOREIGN KEY FK_D9191BD419883967');
        $this->addSql('ALTER TABLE shop_order DROP FOREIGN KEY FK_323FC9CA4C3A3BB');
        $this->addSql('ALTER TABLE sylius_adjustment DROP FOREIGN KEY FK_ACA6E0F2F720C233');
        $this->addSql('ALTER TABLE shop_voucher DROP FOREIGN KEY FK_10A1E5F266C5951B');
        $this->addSql('ALTER TABLE shop_order DROP FOREIGN KEY FK_323FC9CACA0F69C');
        $this->addSql('ALTER TABLE shop_shipment DROP FOREIGN KEY FK_D973DA4A19883967');
        $this->addSql('ALTER TABLE sylius_shipping_method_translation DROP FOREIGN KEY FK_2B37DB3D2C2AC5D3');
        $this->addSql('ALTER TABLE sylius_shipping_method DROP FOREIGN KEY FK_5FB0EE1112469DE2');
        $this->addSql('ALTER TABLE sylius_product_options DROP FOREIGN KEY FK_2B5FF009A7C41D6F');
        $this->addSql('ALTER TABLE sylius_product_option_value DROP FOREIGN KEY FK_F7FF7D4BA7C41D6F');
        $this->addSql('ALTER TABLE sylius_product_option_translation DROP FOREIGN KEY FK_CBA491AD2C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_association_type_translation DROP FOREIGN KEY FK_4F618E52C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_association DROP FOREIGN KEY FK_48E9CDABB1E1C39');
        $this->addSql('ALTER TABLE sylius_product_variant_option_value DROP FOREIGN KEY FK_76CDAFA13B69A9AF');
        $this->addSql('ALTER TABLE sylius_product_variant_translation DROP FOREIGN KEY FK_8DC18EDC2C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_option_value_translation DROP FOREIGN KEY FK_8D4382DC2C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_variant_option_value DROP FOREIGN KEY FK_76CDAFA1D957CA06');
        $this->addSql('ALTER TABLE sylius_product_attribute_value DROP FOREIGN KEY FK_8A053E54B6E62EFA');
        $this->addSql('ALTER TABLE sylius_product_attribute_translation DROP FOREIGN KEY FK_93850EBA2C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_association_product DROP FOREIGN KEY FK_A427B983EFB9C8A5');
        $this->addSql('ALTER TABLE shop_user_address DROP FOREIGN KEY FK_48261619B1835C8F');
        $this->addSql('ALTER TABLE shop_user_address DROP FOREIGN KEY FK_4826161943656FE6');
        $this->addSql('ALTER TABLE shop_order DROP FOREIGN KEY FK_323FC9CAB1835C8F');
        $this->addSql('ALTER TABLE shop_order DROP FOREIGN KEY FK_323FC9CA43656FE6');
        $this->addSql('ALTER TABLE sylius_province DROP FOREIGN KEY FK_B5618FE4F92F3E70');
        $this->addSql('ALTER TABLE sylius_zone_member DROP FOREIGN KEY FK_E8B5ABF34B0E929B');
        $this->addSql('ALTER TABLE sylius_exchange_rate DROP FOREIGN KEY FK_5F52B852A76BEED');
        $this->addSql('ALTER TABLE sylius_exchange_rate DROP FOREIGN KEY FK_5F52B85B3FD5856');
        $this->addSql('ALTER TABLE shop_product DROP FOREIGN KEY FK_D0794487C6CD2B2B');
        $this->addSql('ALTER TABLE sylius_tax_rate DROP FOREIGN KEY FK_3CD86B2E12469DE2');
        $this->addSql('DROP TABLE user_user');
        $this->addSql('DROP TABLE user_user_group');
        $this->addSql('DROP TABLE user_group');
        $this->addSql('DROP TABLE media_usage');
        $this->addSql('DROP TABLE media_format');
        $this->addSql('DROP TABLE media_file');
        $this->addSql('DROP TABLE article_article');
        $this->addSql('DROP TABLE article_category');
        $this->addSql('DROP TABLE page_page');
        $this->addSql('DROP TABLE category_collection');
        $this->addSql('DROP TABLE category_category');
        $this->addSql('DROP TABLE grid_grid');
        $this->addSql('DROP TABLE grid_item');
        $this->addSql('DROP TABLE slider_slider');
        $this->addSql('DROP TABLE slider_slide');
        $this->addSql('DROP TABLE setting_setting');
        $this->addSql('DROP TABLE setting_setting_files');
        $this->addSql('DROP TABLE newsletter_subscriber');
        $this->addSql('DROP TABLE newsletter_subscriber_group');
        $this->addSql('DROP TABLE newsletter_newsletter');
        $this->addSql('DROP TABLE newsletter_group');
        $this->addSql('DROP TABLE calendar_appointment');
        $this->addSql('DROP TABLE content_redirect');
        $this->addSql('DROP TABLE routing_route');
        $this->addSql('DROP TABLE navigation_node');
        $this->addSql('DROP TABLE navigation_navigation');
        $this->addSql('DROP TABLE navigation_link');
        $this->addSql('DROP TABLE project_content');
        $this->addSql('DROP TABLE project_magazine');
        $this->addSql('DROP TABLE project_magazine_pictures');
        $this->addSql('DROP TABLE translation_translation_string');
        $this->addSql('DROP TABLE translation_translation_route');
        $this->addSql('DROP TABLE translation_translation');
        $this->addSql('DROP TABLE shop_voucher');
        $this->addSql('DROP TABLE shop_shipment');
        $this->addSql('DROP TABLE shop_product_association');
        $this->addSql('DROP TABLE shop_product');
        $this->addSql('DROP TABLE sylius_product_options');
        $this->addSql('DROP TABLE shop_promotion');
        $this->addSql('DROP TABLE shop_user_address');
        $this->addSql('DROP TABLE shop_order');
        $this->addSql('DROP TABLE shop_promotion_order');
        $this->addSql('DROP TABLE shop_order_item');
        $this->addSql('DROP TABLE search_data_set');
        $this->addSql('DROP TABLE search_filter');
        $this->addSql('DROP TABLE search_total');
        $this->addSql('DROP TABLE search_index');
        $this->addSql('DROP TABLE grid_item_text_picture');
        $this->addSql('DROP TABLE grid_item_video');
        $this->addSql('DROP TABLE grid_item_cite');
        $this->addSql('DROP TABLE grid_item_picture');
        $this->addSql('DROP TABLE grid_item_gallery');
        $this->addSql('DROP TABLE grid_item_gallery_file');
        $this->addSql('DROP TABLE grid_item_text');
        $this->addSql('DROP TABLE grid_item_two_column');
        $this->addSql('DROP TABLE grid_item_three_column');
        $this->addSql('DROP TABLE grid_item_one_column');
        $this->addSql('DROP TABLE sylius_payment_method_translation');
        $this->addSql('DROP TABLE sylius_payment_method');
        $this->addSql('DROP TABLE sylius_payment');
        $this->addSql('DROP TABLE sylius_order_sequence');
        $this->addSql('DROP TABLE sylius_order_item_unit');
        $this->addSql('DROP TABLE sylius_adjustment');
        $this->addSql('DROP TABLE sylius_promotion_coupon');
        $this->addSql('DROP TABLE sylius_promotion_action');
        $this->addSql('DROP TABLE sylius_promotion_rule');
        $this->addSql('DROP TABLE sylius_shipping_method_translation');
        $this->addSql('DROP TABLE sylius_shipping_method');
        $this->addSql('DROP TABLE sylius_shipping_category');
        $this->addSql('DROP TABLE sylius_shipment_unit');
        $this->addSql('DROP TABLE sylius_locale');
        $this->addSql('DROP TABLE sylius_product_option');
        $this->addSql('DROP TABLE sylius_product_option_value_translation');
        $this->addSql('DROP TABLE sylius_product_association_type');
        $this->addSql('DROP TABLE sylius_product_translation');
        $this->addSql('DROP TABLE sylius_product_variant');
        $this->addSql('DROP TABLE sylius_product_variant_option_value');
        $this->addSql('DROP TABLE sylius_product_variant_translation');
        $this->addSql('DROP TABLE sylius_product_option_value');
        $this->addSql('DROP TABLE sylius_product_association_type_translation');
        $this->addSql('DROP TABLE sylius_product_option_translation');
        $this->addSql('DROP TABLE sylius_product_attribute');
        $this->addSql('DROP TABLE sylius_product_association');
        $this->addSql('DROP TABLE sylius_product_association_product');
        $this->addSql('DROP TABLE sylius_product_attribute_value');
        $this->addSql('DROP TABLE sylius_product_attribute_translation');
        $this->addSql('DROP TABLE sylius_province');
        $this->addSql('DROP TABLE sylius_address');
        $this->addSql('DROP TABLE sylius_zone_member');
        $this->addSql('DROP TABLE sylius_country');
        $this->addSql('DROP TABLE sylius_address_log_entries');
        $this->addSql('DROP TABLE sylius_zone');
        $this->addSql('DROP TABLE sylius_currency');
        $this->addSql('DROP TABLE sylius_exchange_rate');
        $this->addSql('DROP TABLE sylius_inventory_unit');
        $this->addSql('DROP TABLE sylius_tax_rate');
        $this->addSql('DROP TABLE sylius_tax_category');
    }
}
