admin:
    prefix: /admin
    resource: routes/admin/*

admin_api:
    prefix: /admin/api
    resource: routes/admin_api/*

controller:
    resource: ../src/Controller
    type: attribute

endpoint:
    resource: ../src/Endpoint
    type: endpoint
